#version 450

layout(binding = 0, rgba16f) uniform readonly image2D inputImage;
layout(binding = 1, rgba16f) uniform writeonly image2D outputImage;

layout (local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

void main() {
    ivec2 texelCoord = ivec2(gl_GlobalInvocationID.xy);
    vec3 color = vec3(imageLoad(inputImage, texelCoord));
    
    float gray = dot(color, vec3(0.21, 0.71, 0.07));
    imageStore(outputImage, texelCoord, vec4(vec3(gray), 1.0));
}