#version 450

layout(binding = 0, rgba8) uniform readonly image2D inputImage;
layout(binding = 1, rgba8) uniform writeonly image2D outputImage;

layout (local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

void main() {
    ivec2 texelCoord = ivec2(gl_GlobalInvocationID.xy);
    vec4 color = imageLoad(inputImage, texelCoord);

    float gray = dot(color.rgb, vec3(0.299, 0.587, 0.114));
    
    imageStore(outputImage, texelCoord, vec4(vec3(gray), 1.0));
}